#pragma checksum "..\..\AddGuestRequestWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0127C07BA27C09248BFE75C532BAD90A7C9FD8BE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BE;
using PLWPF;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PLWPF {
    
    
    /// <summary>
    /// AddGuestRequestWindow
    /// </summary>
    public partial class AddGuestRequestWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 33 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GuestRequestDeatails;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtGuestRequest;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAdd;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid1;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyPrivateName;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyPrivateName;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label PrivateNameExp;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyFamilyName;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyFamilyName;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label FamilyNameExp;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyMailAdress;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyMailAdress;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MailAdressExp;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyStatus;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyStatus;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyEntryDate;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker datePMyEntryDate;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyReleaseDate;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker datePMyReleaseDate;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyArea;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyArea;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MySubArea;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMySubArea;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Type;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyType;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyADults;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyAdults;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label AdultsExp;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyChildren;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyChildren;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label ChildrenExp;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyPool;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyPool;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyJacuzzi;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyJacuzzi;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyGarden;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyGarden;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MyChildrenAttractions;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\AddGuestRequestWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxMyChildrensAttractions;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PLWPF;component/addguestrequestwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\AddGuestRequestWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "..\..\AddGuestRequestWindow.xaml"
            ((PLWPF.AddGuestRequestWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.GuestRequestDeatails = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.txtGuestRequest = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\AddGuestRequestWindow.xaml"
            this.btnAdd.Click += new System.Windows.RoutedEventHandler(this.btnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\AddGuestRequestWindow.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.btnBack_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.grid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.MyPrivateName = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.txtBoxMyPrivateName = ((System.Windows.Controls.TextBox)(target));
            
            #line 65 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyPrivateName.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyPrivateName_GotFocus);
            
            #line default
            #line hidden
            
            #line 65 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyPrivateName.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyPrivateName_LostFocus);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PrivateNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.MyFamilyName = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.txtBoxMyFamilyName = ((System.Windows.Controls.TextBox)(target));
            
            #line 69 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyFamilyName.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyFamilyName_LostFocus);
            
            #line default
            #line hidden
            
            #line 69 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyFamilyName.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyFamilyName_GotFocus);
            
            #line default
            #line hidden
            return;
            case 12:
            this.FamilyNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.MyMailAdress = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.txtBoxMyMailAdress = ((System.Windows.Controls.TextBox)(target));
            
            #line 73 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyMailAdress.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyMailAdress_GotFocus);
            
            #line default
            #line hidden
            
            #line 73 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyMailAdress.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyMailAdress_LostFocus);
            
            #line default
            #line hidden
            return;
            case 15:
            this.MailAdressExp = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.MyStatus = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.comBoxMyStatus = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.MyEntryDate = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.datePMyEntryDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 79 "..\..\AddGuestRequestWindow.xaml"
            this.datePMyEntryDate.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.datePMyEntryDate_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 20:
            this.MyReleaseDate = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.datePMyReleaseDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 81 "..\..\AddGuestRequestWindow.xaml"
            this.datePMyReleaseDate.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.datePMyReleaseDate_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 22:
            this.MyArea = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.comBoxMyArea = ((System.Windows.Controls.ComboBox)(target));
            
            #line 83 "..\..\AddGuestRequestWindow.xaml"
            this.comBoxMyArea.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.comBoxMyArea_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 24:
            this.MySubArea = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.comBoxMySubArea = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 26:
            this.Type = ((System.Windows.Controls.Label)(target));
            return;
            case 27:
            this.comBoxMyType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 28:
            this.MyADults = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.txtBoxMyAdults = ((System.Windows.Controls.TextBox)(target));
            
            #line 90 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyAdults.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyAdults_LostFocus);
            
            #line default
            #line hidden
            
            #line 90 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyAdults.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyAdults_GotFocus);
            
            #line default
            #line hidden
            return;
            case 30:
            this.AdultsExp = ((System.Windows.Controls.Label)(target));
            return;
            case 31:
            this.MyChildren = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.txtBoxMyChildren = ((System.Windows.Controls.TextBox)(target));
            
            #line 94 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyChildren.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyChildren_GotFocus);
            
            #line default
            #line hidden
            
            #line 94 "..\..\AddGuestRequestWindow.xaml"
            this.txtBoxMyChildren.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyChildren_LostFocus);
            
            #line default
            #line hidden
            return;
            case 33:
            this.ChildrenExp = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.MyPool = ((System.Windows.Controls.Label)(target));
            return;
            case 35:
            this.comBoxMyPool = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 36:
            this.MyJacuzzi = ((System.Windows.Controls.Label)(target));
            return;
            case 37:
            this.comBoxMyJacuzzi = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 38:
            this.MyGarden = ((System.Windows.Controls.Label)(target));
            return;
            case 39:
            this.comBoxMyGarden = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 40:
            this.MyChildrenAttractions = ((System.Windows.Controls.Label)(target));
            return;
            case 41:
            this.comBoxMyChildrensAttractions = ((System.Windows.Controls.ComboBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

