#pragma checksum "..\..\AddHostingUnitWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "78364DE2272205E2C34281471D572FD12AF45E6B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BE;
using PLWPF;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PLWPF {
    
    
    /// <summary>
    /// AddHostingUnitWindow
    /// </summary>
    public partial class AddHostingUnitWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 33 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid HostingUnitDeatails;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtHostingUnit;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAdd;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid1;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyHostingUnitName;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label HostingNameExp;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmBoxMyArea;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid2;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyHostKey;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label HostKeyExp;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyPrivateName;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label PrivateNameExp;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyFamilyName;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label FamilyNameExp;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyFhoneNumber;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label FhoneNumExp;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyMailAddress;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MailExp;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBankAccountNumber;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label BankAccountNumExp;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChckBoxMyCollectionClearance;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid3;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbBoxMyBankName;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBankNumber;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbBoxMyBranchNumber;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBranchAddress;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBranchCity;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\AddHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar progressBar;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PLWPF;component/addhostingunitwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\AddHostingUnitWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "..\..\AddHostingUnitWindow.xaml"
            ((PLWPF.AddHostingUnitWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.HostingUnitDeatails = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.txtHostingUnit = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\AddHostingUnitWindow.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.btnBack_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\AddHostingUnitWindow.xaml"
            this.btnAdd.Click += new System.Windows.RoutedEventHandler(this.btnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.grid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.txtBoxMyHostingUnitName = ((System.Windows.Controls.TextBox)(target));
            
            #line 51 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyHostingUnitName.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyHostingUnitName_GotFocus);
            
            #line default
            #line hidden
            
            #line 51 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyHostingUnitName.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyHostingUnitName_LostFocus);
            
            #line default
            #line hidden
            return;
            case 8:
            this.HostingNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.cmBoxMyArea = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.grid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.txtBoxMyHostKey = ((System.Windows.Controls.TextBox)(target));
            
            #line 75 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyHostKey.GotFocus += new System.Windows.RoutedEventHandler(this.myHostKeyTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 75 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyHostKey.LostFocus += new System.Windows.RoutedEventHandler(this.myHostKeyTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 12:
            this.HostKeyExp = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.txtBoxMyPrivateName = ((System.Windows.Controls.TextBox)(target));
            
            #line 79 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyPrivateName.GotFocus += new System.Windows.RoutedEventHandler(this.myPrivateNameTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 79 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyPrivateName.LostFocus += new System.Windows.RoutedEventHandler(this.myPrivateNameTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 14:
            this.PrivateNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.txtBoxMyFamilyName = ((System.Windows.Controls.TextBox)(target));
            
            #line 83 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyFamilyName.GotFocus += new System.Windows.RoutedEventHandler(this.myFamilyNameTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 83 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyFamilyName.LostFocus += new System.Windows.RoutedEventHandler(this.myFamilyNameTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 16:
            this.FamilyNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.txtBoxMyFhoneNumber = ((System.Windows.Controls.TextBox)(target));
            
            #line 87 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyFhoneNumber.LostFocus += new System.Windows.RoutedEventHandler(this.myFhoneNumberTextBox_LostFocus);
            
            #line default
            #line hidden
            
            #line 87 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyFhoneNumber.GotFocus += new System.Windows.RoutedEventHandler(this.myFhoneNumberTextBox_GotFocus);
            
            #line default
            #line hidden
            return;
            case 18:
            this.FhoneNumExp = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.txtBoxMyMailAddress = ((System.Windows.Controls.TextBox)(target));
            
            #line 91 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyMailAddress.GotFocus += new System.Windows.RoutedEventHandler(this.myMailAddressTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 91 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyMailAddress.LostFocus += new System.Windows.RoutedEventHandler(this.myMailAddressTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 20:
            this.MailExp = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.txtBoxMyBankAccountNumber = ((System.Windows.Controls.TextBox)(target));
            
            #line 95 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyBankAccountNumber.LostFocus += new System.Windows.RoutedEventHandler(this.myBankAccountNumberTextBox_LostFocus);
            
            #line default
            #line hidden
            
            #line 95 "..\..\AddHostingUnitWindow.xaml"
            this.txtBoxMyBankAccountNumber.GotFocus += new System.Windows.RoutedEventHandler(this.myBankAccountNumberTextBox_GotFocus);
            
            #line default
            #line hidden
            return;
            case 22:
            this.BankAccountNumExp = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.ChckBoxMyCollectionClearance = ((System.Windows.Controls.CheckBox)(target));
            
            #line 99 "..\..\AddHostingUnitWindow.xaml"
            this.ChckBoxMyCollectionClearance.Checked += new System.Windows.RoutedEventHandler(this.myCollectionClearanceCheckBox_Checked);
            
            #line default
            #line hidden
            return;
            case 24:
            this.grid3 = ((System.Windows.Controls.Grid)(target));
            return;
            case 25:
            this.cmbBoxMyBankName = ((System.Windows.Controls.ComboBox)(target));
            
            #line 117 "..\..\AddHostingUnitWindow.xaml"
            this.cmbBoxMyBankName.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cmbBoxMyBankName_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 26:
            this.txtBoxMyBankNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.cmbBoxMyBranchNumber = ((System.Windows.Controls.ComboBox)(target));
            
            #line 123 "..\..\AddHostingUnitWindow.xaml"
            this.cmbBoxMyBranchNumber.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cmbBoxMyBranchNumber_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 28:
            this.txtBoxMyBranchAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.txtBoxMyBranchCity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.progressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

