#pragma checksum "..\..\MoreOptionsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8C83EB6EAE54CC610E8EAA20DF0829CC256C581F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PLWPF;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PLWPF {
    
    
    /// <summary>
    /// MoreOptionsWindow
    /// </summary>
    public partial class MoreOptionsWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 27 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGRlst;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHUlst;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnORlst;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGuestByArea;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGuestByPeople;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHostByHosting;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHostingByArea;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\MoreOptionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContentControl page;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PLWPF;component/moreoptionswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MoreOptionsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btnGRlst = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\MoreOptionsWindow.xaml"
            this.btnGRlst.Click += new System.Windows.RoutedEventHandler(this.btnGRlst_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnHUlst = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\MoreOptionsWindow.xaml"
            this.btnHUlst.Click += new System.Windows.RoutedEventHandler(this.btnHUlst_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnORlst = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\MoreOptionsWindow.xaml"
            this.btnORlst.Click += new System.Windows.RoutedEventHandler(this.btnORlst_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnGuestByArea = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\MoreOptionsWindow.xaml"
            this.btnGuestByArea.Click += new System.Windows.RoutedEventHandler(this.BtnGuestByArea_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnGuestByPeople = ((System.Windows.Controls.Button)(target));
            
            #line 32 "..\..\MoreOptionsWindow.xaml"
            this.btnGuestByPeople.Click += new System.Windows.RoutedEventHandler(this.btnGuestByPeople_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btnHostByHosting = ((System.Windows.Controls.Button)(target));
            
            #line 33 "..\..\MoreOptionsWindow.xaml"
            this.btnHostByHosting.Click += new System.Windows.RoutedEventHandler(this.btnHostByHosting_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btnHostingByArea = ((System.Windows.Controls.Button)(target));
            
            #line 34 "..\..\MoreOptionsWindow.xaml"
            this.btnHostingByArea.Click += new System.Windows.RoutedEventHandler(this.btnHostingByArea_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.page = ((System.Windows.Controls.ContentControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

