#pragma checksum "..\..\OrderWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E746C94B2212E0CB4AFFF9DD9CDEBF92E42D00CB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PLWPF;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PLWPF {
    
    
    /// <summary>
    /// OrderWindow
    /// </summary>
    public partial class OrderWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 26 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtSelect;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtOrder;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBoxChoosing;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxStatus;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComBoxType;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComBoxArea;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Clear;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GuestRequestDataGrid;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxChoosing;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAdd;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lstBox;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\OrderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PLWPF;component/orderwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\OrderWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtSelect = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.txtOrder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.txtBoxChoosing = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.comBoxStatus = ((System.Windows.Controls.ComboBox)(target));
            
            #line 34 "..\..\OrderWindow.xaml"
            this.comBoxStatus.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.comBoxStatus_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ComBoxType = ((System.Windows.Controls.ComboBox)(target));
            
            #line 36 "..\..\OrderWindow.xaml"
            this.ComBoxType.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ComBoxType_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ComBoxArea = ((System.Windows.Controls.ComboBox)(target));
            
            #line 38 "..\..\OrderWindow.xaml"
            this.ComBoxArea.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ComBoxArea_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.Clear = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\OrderWindow.xaml"
            this.Clear.Click += new System.Windows.RoutedEventHandler(this.Clear_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.GuestRequestDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 11:
            this.comBoxChoosing = ((System.Windows.Controls.ComboBox)(target));
            
            #line 74 "..\..\OrderWindow.xaml"
            this.comBoxChoosing.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.comBoxChoosing_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 75 "..\..\OrderWindow.xaml"
            this.btnAdd.Click += new System.Windows.RoutedEventHandler(this.btnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            
            #line 76 "..\..\OrderWindow.xaml"
            this.btnUpdate.Click += new System.Windows.RoutedEventHandler(this.btnUpdate_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.lstBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 77 "..\..\OrderWindow.xaml"
            this.lstBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.lstBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 78 "..\..\OrderWindow.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.btnBack_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 9:
            
            #line 49 "..\..\OrderWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.select_Click);
            
            #line default
            #line hidden
            break;
            case 10:
            
            #line 67 "..\..\OrderWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.details_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

