#pragma checksum "..\..\UpdateHostingUnitWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7F649D695AB94BC8FEF36E53885FCD819C6636F0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BE;
using PLWPF;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PLWPF {
    
    
    /// <summary>
    /// UpdateHostingUnitWindow
    /// </summary>
    public partial class UpdateHostingUnitWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 43 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid HostingUnitDeatails;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtHostingUnit;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid1;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyHostingUnitKey;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyHostingUnitName;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label HostingNameExp;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmBoxMyArea;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid2;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyHostKey;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label HostKeyExp;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyPrivateName;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label PrivateNameExp;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyFamilyName;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label FamilyNameExp;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyFhoneNumber;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label FhoneNumExp;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyMailAddress;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label MailExp;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBankAccountNumber;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label BankAccountNumExp;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChckBoxMyCollectionClearance;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid3;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBankName;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBankNumber;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBranchNumber;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBranchAddress;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxMyBranchCity;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label ChoseHostingUnit;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\UpdateHostingUnitWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comBoxChoosing;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PLWPF;component/updatehostingunitwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\UpdateHostingUnitWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "..\..\UpdateHostingUnitWindow.xaml"
            ((PLWPF.UpdateHostingUnitWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.HostingUnitDeatails = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.txtHostingUnit = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\UpdateHostingUnitWindow.xaml"
            this.btnUpdate.Click += new System.Windows.RoutedEventHandler(this.btnUpdate_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\UpdateHostingUnitWindow.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.btnBack_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.grid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.txtBoxMyHostingUnitKey = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtBoxMyHostingUnitName = ((System.Windows.Controls.TextBox)(target));
            
            #line 65 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyHostingUnitName.GotFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyHostingUnitName_GotFocus);
            
            #line default
            #line hidden
            
            #line 65 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyHostingUnitName.LostFocus += new System.Windows.RoutedEventHandler(this.txtBoxMyHostingUnitName_LostFocus);
            
            #line default
            #line hidden
            return;
            case 9:
            this.HostingNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.cmBoxMyArea = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.grid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.txtBoxMyHostKey = ((System.Windows.Controls.TextBox)(target));
            
            #line 88 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyHostKey.GotFocus += new System.Windows.RoutedEventHandler(this.myHostKeyTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 88 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyHostKey.LostFocus += new System.Windows.RoutedEventHandler(this.myHostKeyTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 13:
            this.HostKeyExp = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.txtBoxMyPrivateName = ((System.Windows.Controls.TextBox)(target));
            
            #line 92 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyPrivateName.GotFocus += new System.Windows.RoutedEventHandler(this.myPrivateNameTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 92 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyPrivateName.LostFocus += new System.Windows.RoutedEventHandler(this.myPrivateNameTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 15:
            this.PrivateNameExp = ((System.Windows.Controls.Label)(target));
            
            #line 93 "..\..\UpdateHostingUnitWindow.xaml"
            this.PrivateNameExp.LostFocus += new System.Windows.RoutedEventHandler(this.myFamilyNameTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 16:
            this.txtBoxMyFamilyName = ((System.Windows.Controls.TextBox)(target));
            
            #line 96 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyFamilyName.GotFocus += new System.Windows.RoutedEventHandler(this.myFamilyNameTextBox_GotFocus);
            
            #line default
            #line hidden
            return;
            case 17:
            this.FamilyNameExp = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.txtBoxMyFhoneNumber = ((System.Windows.Controls.TextBox)(target));
            
            #line 100 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyFhoneNumber.GotFocus += new System.Windows.RoutedEventHandler(this.myFhoneNumberTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 100 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyFhoneNumber.LostFocus += new System.Windows.RoutedEventHandler(this.myFhoneNumberTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 19:
            this.FhoneNumExp = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.txtBoxMyMailAddress = ((System.Windows.Controls.TextBox)(target));
            
            #line 104 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyMailAddress.GotFocus += new System.Windows.RoutedEventHandler(this.myMailAddressTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 104 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyMailAddress.LostFocus += new System.Windows.RoutedEventHandler(this.myMailAddressTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 21:
            this.MailExp = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.txtBoxMyBankAccountNumber = ((System.Windows.Controls.TextBox)(target));
            
            #line 108 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyBankAccountNumber.GotFocus += new System.Windows.RoutedEventHandler(this.myBankAccountNumberTextBox_GotFocus);
            
            #line default
            #line hidden
            
            #line 108 "..\..\UpdateHostingUnitWindow.xaml"
            this.txtBoxMyBankAccountNumber.LostFocus += new System.Windows.RoutedEventHandler(this.myBankAccountNumberTextBox_LostFocus);
            
            #line default
            #line hidden
            return;
            case 23:
            this.BankAccountNumExp = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.ChckBoxMyCollectionClearance = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.grid3 = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.txtBoxMyBankName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.txtBoxMyBankNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.txtBoxMyBranchNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.txtBoxMyBranchAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.txtBoxMyBranchCity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.ChoseHostingUnit = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.comBoxChoosing = ((System.Windows.Controls.ComboBox)(target));
            
            #line 144 "..\..\UpdateHostingUnitWindow.xaml"
            this.comBoxChoosing.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.comBoxChoosing_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

